# Changes here will be overwritten by Copier
_commit: v0.0.12
_src_path: https://github.com/AmpelAstro/copier-ampel.git
author_email: jakob.van.santen@desy.de
author_name: Jakob van Santen
plugin_description: Legacy Survey of Space and Time support for the Ampel system
plugin_name: LSST
plugin_org: AmpelAstro
plugin_version: 0.10.1a8
version_cap: <0.11
